graph LR;

Frog["fa:fa-frog"] --> FrogService
FrogService["Frog Service"] --> PondService["Pond Service"]
FrogService["Frog Service"] --> WeatherService["Weather Service"]
FrogService["Frog Service"] --> GroupChatService["Group Chat Service"]
PondService["Pond Service"] --> FoodService["Food Service"]
PondService["Pond Service"] --> LilypadService["Lilypad Service"]

